name: Dev to Int Workflow

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  dev-to-int:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.4

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Linter
        run: pnpm run lint

      - name: Run Formatter Check
        run: pnpm run format:check

      - name: Run Tests and Check Coverage
        run: |
          pnpm test -- --coverage
          if [ $(pnpm test -- --coverage | grep -oP '(?<=All files \|)\s*\d+(\.\d+)?(?=\s*\|)' | awk '{print int($1)}') -lt 95 ]; then
            echo "Test coverage is below 95%. Failing the build."
            exit 1
          fi

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: int
          title: 'Merge dev into int'
          body: |
            This PR was automatically created by the CI workflow. All linting, style checks, and tests have passed on the dev branch.

            Changes in this PR:
            ${{ github.event.head_commit.message }}

            For a full list of changes, please review the commits in this PR.
          labels: automated-pr
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          delete-branch: true
