name: Test and PR
on:
  push:
    branches:
      - stage
jobs:
  test-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          # Add your test commands here
          echo "Running tests..."
      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: 'Merge stage into main'
          body: 'This PR was automatically created by the CI workflow. All tests have passed on the stage branch.'
